# -*- coding: utf-8 -*-
import os
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE)

q34 = chr(34)
q39 = chr(39)

def w(rel, content):
    fp = os.path.join(BASE, rel)
    os.makedirs(os.path.dirname(fp), exist_ok=True)
    with open(fp, 'w', encoding='utf-8') as f:
        f.write(content)
    print('Created: ' + rel)

# ===== app.py =====
app_lines = []
app_lines.append('# -*- coding: utf-8 -*-')
app_lines.append('from flask import Flask, render_template, request, jsonify')
app_lines.append('import os')
app_lines.append('import sys')
app_lines.append('')
app_lines.append('sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))')
app_lines.append('from utils.db import init_database, get_all_teams, get_all_equipments, get_alerts, get_dashboard_stats, get_connection')
app_lines.append('from utils.excel import import_shipping_plan, import_production_cycles, import_work_orders, import_processes, import_bom')
app_lines.append('from utils.calc import calculate_alerts, back_calculate_semi, calculate_quantity')
app_lines.append('')
app_lines.append('app = Flask(__name__)')
app_lines.append('app.config[' + q34 + 'UPLOAD_FOLDER' + q34 + '] = os.path.join(os.path.dirname(__file__), ' + q34 + 'imports' + q34 + ')')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/' + q39 + ')')
app_lines.append('def index():')
app_lines.append('    return render_template(' + q39 + 'index.html' + q39 + ')')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/dashboard' + q39 + ')')
app_lines.append('def api_dashboard():')
app_lines.append('    stats = get_dashboard_stats()')
app_lines.append('    return jsonify(stats)')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/alerts' + q39 + ')')
app_lines.append('def api_alerts():')
app_lines.append('    level = request.args.get(' + q39 + 'level' + q39 + ')')
app_lines.append('    alerts = get_alerts(level)')
app_lines.append('    return jsonify(alerts)')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/alerts/calculate' + q39 + ', methods=[' + q39 + 'POST' + q39 + '])')
app_lines.append('def api_calc_alerts():')
app_lines.append('    count = calculate_alerts()')
app_lines.append('    return jsonify({' + q39 + 'count' + q39 + ': count})')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/back-calculate' + q39 + ', methods=[' + q39 + 'POST' + q39 + '])')
app_lines.append('def api_back_calc():')
app_lines.append('    count = back_calculate_semi()')
app_lines.append('    return jsonify({' + q39 + 'new_orders' + q39 + ': count})')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/teams' + q39 + ')')
app_lines.append('def api_teams():')
app_lines.append('    return jsonify(get_all_teams())')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/equipments' + q39 + ')')
app_lines.append('def api_equipments():')
app_lines.append('    team_id = request.args.get(' + q39 + 'team_id' + q39 + ', type=int)')
app_lines.append('    return jsonify(get_all_equipments(team_id))')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/import/<data_type>' + q39 + ', methods=[' + q39 + 'POST' + q39 + '])')
app_lines.append('def api_import(data_type):')
app_lines.append('    if ' + q39 + 'file' + q39 + ' not in request.files:')
app_lines.append('        return jsonify({' + q39 + 'error' + q39 + ': ' + q39 + 'no file' + q39 + '}), 400')
app_lines.append('    f = request.files[' + q39 + 'file' + q39 + ']')
app_lines.append('    path = os.path.join(app.config[' + q34 + 'UPLOAD_FOLDER' + q34 + '], f.filename)')
app_lines.append('    os.makedirs(app.config[' + q34 + 'UPLOAD_FOLDER' + q34 + '], exist_ok=True)')
app_lines.append('    f.save(path)')
app_lines.append('    try:')
app_lines.append('        if data_type == ' + q39 + 'shipping' + q39 + ':')
app_lines.append('            count = import_shipping_plan(path)')
app_lines.append('        elif data_type == ' + q39 + 'cycles' + q39 + ':')
app_lines.append('            count = import_production_cycles(path)')
app_lines.append('        elif data_type == ' + q39 + 'orders' + q39 + ':')
app_lines.append('            count = import_work_orders(path)')
app_lines.append('        elif data_type == ' + q39 + 'processes' + q39 + ':')
app_lines.append('            count = import_processes(path)')
app_lines.append('        elif data_type == ' + q39 + 'bom' + q39 + ':')
app_lines.append('            count = import_bom(path)')
app_lines.append('        else:')
app_lines.append('            return jsonify({' + q39 + 'error' + q39 + ': ' + q39 + 'unknown type' + q39 + '}), 400')
app_lines.append('        return jsonify({' + q39 + 'count' + q39 + ': count})')
app_lines.append('    except Exception as e:')
app_lines.append('        return jsonify({' + q39 + 'error' + q39 + ': str(e)}), 500')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/schedule' + q39 + ', methods=[' + q39 + 'GET' + q39 + '])')
app_lines.append('def api_schedule_list():')
app_lines.append('    conn = get_connection()')
app_lines.append('    c = conn.cursor()')
app_lines.append('    team_id = request.args.get(' + q39 + 'team_id' + q39 + ', type=int)')
app_lines.append('    date = request.args.get(' + q39 + 'date' + q39 + ')')
app_lines.append('    q = ' + q34 + 'SELECT s.*, e.equipment_name FROM schedules s LEFT JOIN equipments e ON s.equipment_id=e.id WHERE 1=1' + q34)
app_lines.append('    params = []')
app_lines.append('    if team_id:')
app_lines.append('        q += ' + q34 + ' AND s.team_id=?' + q34)
app_lines.append('        params.append(team_id)')
app_lines.append('    if date:')
app_lines.append('        q += ' + q34 + ' AND s.schedule_date=?' + q34)
app_lines.append('        params.append(date)')
app_lines.append('    c.execute(q, params)')
app_lines.append('    r = [dict(row) for row in c.fetchall()]')
app_lines.append('    conn.close()')
app_lines.append('    return jsonify(r)')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/schedule' + q39 + ', methods=[' + q39 + 'POST' + q39 + '])')
app_lines.append('def api_schedule_create():')
app_lines.append('    data = request.json')
app_lines.append('    conn = get_connection()')
app_lines.append('    c = conn.cursor()')
app_lines.append('    c.execute(' + q34 + 'INSERT INTO schedules (equipment_id, work_order_no, process_code, process_name, schedule_date, start_time, end_time, quantity, hours, capacity_per_hour, is_overtime, team_id, task_status, priority) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' + q34 + ', (data.get(' + q39 + 'equipment_id' + q39 + '), data.get(' + q39 + 'work_order_no' + q39 + '), data.get(' + q39 + 'process_code' + q39 + '), data.get(' + q39 + 'process_name' + q39 + '), data.get(' + q39 + 'schedule_date' + q39 + '), data.get(' + q39 + 'start_time' + q39 + '), data.get(' + q39 + 'end_time' + q39 + '), data.get(' + q39 + 'quantity' + q39 + ', 0), data.get(' + q39 + 'hours' + q39 + ', 0), data.get(' + q39 + 'capacity_per_hour' + q39 + ', 0), data.get(' + q39 + 'is_overtime' + q39 + ', 0), data.get(' + q39 + 'team_id' + q39 + '), ' + q39 + 'planned' + q39 + ', data.get(' + q39 + 'priority' + q39 + ', ' + q39 + 'P2' + q39 + ')))')
app_lines.append('    conn.commit()')
app_lines.append('    new_id = c.lastrowid')
app_lines.append('    conn.close()')
app_lines.append('    return jsonify({' + q39 + 'id' + q39 + ': new_id})')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/schedule/<int:sid>' + q39 + ', methods=[' + q39 + 'PUT' + q39 + '])')
app_lines.append('def api_schedule_update(sid):')
app_lines.append('    data = request.json')
app_lines.append('    conn = get_connection()')
app_lines.append('    c = conn.cursor()')
app_lines.append('    c.execute(' + q34 + 'UPDATE schedules SET equipment_id=?, start_time=?, end_time=?, quantity=?, hours=?, capacity_per_hour=?, is_overtime=? WHERE id=?' + q34 + ', (data.get(' + q39 + 'equipment_id' + q39 + '), data.get(' + q39 + 'start_time' + q39 + '), data.get(' + q39 + 'end_time' + q39 + '), data.get(' + q39 + 'quantity' + q39 + ', 0), data.get(' + q39 + 'hours' + q39 + ', 0), data.get(' + q39 + 'capacity_per_hour' + q39 + ', 0), data.get(' + q39 + 'is_overtime' + q39 + ', 0), sid))')
app_lines.append('    conn.commit()')
app_lines.append('    conn.close()')
app_lines.append('    return jsonify({' + q39 + 'ok' + q39 + ': True})')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/schedule/<int:sid>' + q39 + ', methods=[' + q39 + 'DELETE' + q39 + '])')
app_lines.append('def api_schedule_delete(sid):')
app_lines.append('    conn = get_connection()')
app_lines.append('    c = conn.cursor()')
app_lines.append('    c.execute(' + q34 + 'DELETE FROM schedules WHERE id=?' + q34 + ', (sid,))')
app_lines.append('    conn.commit()')
app_lines.append('    conn.close()')
app_lines.append('    return jsonify({' + q39 + 'ok' + q39 + ': True})')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/orders' + q39 + ')')
app_lines.append('def api_orders():')
app_lines.append('    conn = get_connection()')
app_lines.append('    c = conn.cursor()')
app_lines.append('    status = request.args.get(' + q39 + 'status' + q39 + ')')
app_lines.append('    if status:')
app_lines.append('        c.execute(' + q34 + 'SELECT * FROM work_orders WHERE status=? ORDER BY due_date' + q34 + ', (status,))')
app_lines.append('    else:')
app_lines.append('        c.execute(' + q34 + 'SELECT * FROM work_orders ORDER BY due_date' + q34 + ')')
app_lines.append('    r = [dict(row) for row in c.fetchall()]')
app_lines.append('    conn.close()')
app_lines.append('    return jsonify(r)')
app_lines.append('')
app_lines.append('@app.route(' + q39 + '/api/statistics' + q39 + ')')
app_lines.append('def api_statistics():')
app_lines.append('    conn = get_connection()')
app_lines.append('    c = conn.cursor()')
app_lines.append('    c.execute(' + q34 + 'SELECT team_id, SUM(quantity) as planned, SUM(CASE WHEN task_status=? THEN quantity ELSE 0 END) as completed FROM schedules GROUP BY team_id' + q34 + ', (' + q39 + 'completed' + q39 + ',))')
app_lines.append('    stats = [dict(row) for row in c.fetchall()]')
app_lines.append('    conn.close()')
app_lines.append('    return jsonify(stats)')
app_lines.append('')
app_lines.append('if __name__ == ' + q34 + '__main__' + q34 + ':')
app_lines.append('    init_database()')
app_lines.append('    app.run(debug=True, host=' + q34 + '0.0.0.0' + q34 + ', port=5000)')

w('app.py', chr(10).join(app_lines))
print('builder3 done!')