# -*- coding: utf-8 -*-
import os
import openpyxl
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE)

q34 = chr(34)
q39 = chr(39)
lp = chr(40)
rp = chr(41)

def w(rel, content):
    fp = os.path.join(BASE, rel)
    os.makedirs(os.path.dirname(fp), exist_ok=True)
    with open(fp, 'w', encoding='utf-8') as f:
        f.write(content)
    print('Created: ' + rel)

# ===== 1. utils/excel.py =====
ex_lines = []
ex_lines.append('# -*- coding: utf-8 -*-')
ex_lines.append('import openpyxl')
ex_lines.append('import os')
ex_lines.append('import sys')
ex_lines.append('')
ex_lines.append('sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))')
ex_lines.append('from utils.db import get_connection')
ex_lines.append('')
ex_lines.append('def read_excel(file_path, sheet_name=None):')
ex_lines.append('    wb = openpyxl.load_workbook(file_path)')
ex_lines.append('    if sheet_name:')
ex_lines.append('        ws = wb[sheet_name]')
ex_lines.append('    else:')
ex_lines.append('        ws = wb.active')
ex_lines.append('    headers = [cell.value for cell in ws[1]]')
ex_lines.append('    data = []')
ex_lines.append('    for row in ws.iter_rows(min_row=2, values_only=True):')
ex_lines.append('        if any(row):')
ex_lines.append('            data.append(dict(zip(headers, row)))')
ex_lines.append('    return data')
ex_lines.append('')
ex_lines.append('def import_shipping_plan(file_path):')
ex_lines.append('    wb = openpyxl.load_workbook(file_path)')
ex_lines.append('    ws = wb.active')
ex_lines.append('    conn = get_connection()')
ex_lines.append('    c = conn.cursor()')
ex_lines.append('    c.execute(' + q34 + 'DELETE FROM shipping_plan' + q34 + ')')
ex_lines.append('    headers = [cell.value for cell in ws[1]]')
ex_lines.append('    dates = []')
ex_lines.append('    for i, h in enumerate(headers):')
ex_lines.append('        if hasattr(h, ' + q39 + 'strftime' + q39 + '):')
ex_lines.append('            dates.append((i, h))')
ex_lines.append('    count = 0')
ex_lines.append('    for row in ws.iter_rows(min_row=2, values_only=True):')
ex_lines.append('        if not row or not row[0]:')
ex_lines.append('            continue')
ex_lines.append('        product_code = str(row[0]).strip()')
ex_lines.append('        for col_idx, ship_date in dates:')
ex_lines.append('            qty = row[col_idx] if col_idx < len(row) else None')
ex_lines.append('            if qty and str(qty).isdigit() and int(qty) > 0:')
ex_lines.append('                date_str = ship_date.strftime(' + q39 + '%Y-%m-%d' + q39 + ')')
ex_lines.append('                c.execute(' + q34 + 'INSERT INTO shipping_plan (product_code, quantity, ship_date) VALUES (?, ?, ?)' + q34 + ', (product_code, int(qty), date_str))')
ex_lines.append('                count += 1')
ex_lines.append('    conn.commit()')
ex_lines.append('    conn.close()')
ex_lines.append('    return count')
ex_lines.append('')
ex_lines.append('def import_production_cycles(file_path):')
ex_lines.append('    wb = openpyxl.load_workbook(file_path)')
ex_lines.append('    ws = wb.active')
ex_lines.append('    conn = get_connection()')
ex_lines.append('    c = conn.cursor()')
ex_lines.append('    c.execute(' + q34 + 'DELETE FROM production_cycles' + q34 + ')')
ex_lines.append('    count = 0')
ex_lines.append('    for row in ws.iter_rows(min_row=2, values_only=True):')
ex_lines.append('        if not row or not row[0]:')
ex_lines.append('            continue')
ex_lines.append('        product_code = str(row[0]).strip()')
ex_lines.append('        prod_days = row[1] if row[1] else 1')
ex_lines.append('        lead_days = row[2] if row[2] else 0')
ex_lines.append('        c.execute(' + q34 + 'INSERT INTO production_cycles (product_code, production_days, lead_days) VALUES (?, ?, ?)' + q34 + ', (product_code, prod_days, lead_days))')
ex_lines.append('        count += 1')
ex_lines.append('    conn.commit()')
ex_lines.append('    conn.close()')
ex_lines.append('    return count')
ex_lines.append('')
ex_lines.append('def import_work_orders(file_path):')
ex_lines.append('    wb = openpyxl.load_workbook(file_path)')
ex_lines.append('    ws = wb.active')
ex_lines.append('    conn = get_connection()')
ex_lines.append('    c = conn.cursor()')
ex_lines.append('    count = 0')
ex_lines.append('    for row in ws.iter_rows(min_row=2, values_only=True):')
ex_lines.append('        if not row or not row[0]:')
ex_lines.append('            continue')
ex_lines.append('        order_no = str(row[0]).strip()')
ex_lines.append('        product_code = str(row[2]).strip() if row[2] else ' + q39 + q39)
ex_lines.append('        product_name = str(row[2]).strip() if row[2] else ' + q39 + q39)
ex_lines.append('        quantity = row[5] if row[5] else 0')
ex_lines.append('        priority = str(row[6]).strip() if row[6] else ' + q39 + 'P2' + q39)
ex_lines.append('        due_date = row[10].strftime(' + q39 + '%Y-%m-%d' + q39 + ') if hasattr(row[10], ' + q39 + 'strftime' + q39 + ') else str(row[10]) if row[10] else None')
ex_lines.append('        c.execute(' + q34 + 'INSERT OR REPLACE INTO work_orders (order_no, product_code, product_name, quantity, due_date, priority, status) VALUES (?, ?, ?, ?, ?, ?, ?)' + q34 + ', (order_no, product_code, product_name, quantity, due_date, priority, ' + q39 + 'pending' + q39 + '))')
ex_lines.append('        count += 1')
ex_lines.append('    conn.commit()')
ex_lines.append('    conn.close()')
ex_lines.append('    return count')
ex_lines.append('')
ex_lines.append('def import_processes(file_path):')
ex_lines.append('    wb = openpyxl.load_workbook(file_path)')
ex_lines.append('    ws = wb.active')
ex_lines.append('    conn = get_connection()')
ex_lines.append('    c = conn.cursor()')
ex_lines.append('    c.execute(' + q34 + 'DELETE FROM processes' + q34 + ')')
ex_lines.append('    count = 0')
ex_lines.append('    for row in ws.iter_rows(min_row=2, values_only=True):')
ex_lines.append('        if not row or not row[0]:')
ex_lines.append('            continue')
ex_lines.append('        process_code = str(row[0]).strip()')
ex_lines.append('        process_name = str(row[1]).strip() if row[1] else ' + q39 + q39)
ex_lines.append('        team_name = str(row[2]).strip() if row[2] else None')
ex_lines.append('        c.execute(' + q34 + 'INSERT OR REPLACE INTO processes (process_code, process_name, team_name) VALUES (?, ?, ?)' + q34 + ', (process_code, process_name, team_name))')
ex_lines.append('        count += 1')
ex_lines.append('    conn.commit()')
ex_lines.append('    conn.close()')
ex_lines.append('    return count')
ex_lines.append('')
ex_lines.append('def import_bom(file_path):')
ex_lines.append('    wb = openpyxl.load_workbook(file_path)')
ex_lines.append('    ws = wb.active')
ex_lines.append('    conn = get_connection()')
ex_lines.append('    c = conn.cursor()')
ex_lines.append('    c.execute(' + q34 + 'DELETE FROM bom' + q34 + ')')
ex_lines.append('    count = 0')
ex_lines.append('    for row in ws.iter_rows(min_row=2, values_only=True):')
ex_lines.append('        if not row or not row[0]:')
ex_lines.append('            continue')
ex_lines.append('        parent_code = str(row[0]).strip()')
ex_lines.append('        parent_name = str(row[1]).strip() if row[1] else ' + q39 + q39)
ex_lines.append('        child_code = str(row[5]).strip() if row[5] else ' + q39 + q39)
ex_lines.append('        child_name = str(row[6]).strip() if row[6] else ' + q39 + q39)
ex_lines.append('        qty = abs(float(row[8])) if row[8] else 1')
ex_lines.append('        unit = str(row[9]).strip() if row[9] else ' + q39 + '' + q39)
ex_lines.append('        process_team = str(row[11]).strip() if row[11] else None')
ex_lines.append('        c.execute(' + q34 + 'INSERT INTO bom (parent_product_code, parent_product_name, child_product_code, child_product_name, quantity, unit, process_team) VALUES (?, ?, ?, ?, ?, ?, ?)' + q34 + ', (parent_code, parent_name, child_code, child_name, qty, unit, process_team))')
ex_lines.append('        count += 1')
ex_lines.append('    conn.commit()')
ex_lines.append('    conn.close()')
ex_lines.append('    return count')

w('utils/excel.py', chr(10).join(ex_lines))

# ===== 2. utils/calc.py =====
calc_lines = []
calc_lines.append('# -*- coding: utf-8 -*-')
calc_lines.append('import os')
calc_lines.append('import sys')
calc_lines.append('from datetime import datetime, timedelta')
calc_lines.append('')
calc_lines.append('sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))')
calc_lines.append('from utils.db import get_connection')
calc_lines.append('')
calc_lines.append('def calculate_alerts():')
calc_lines.append('    conn = get_connection()')
calc_lines.append('    c = conn.cursor()')
calc_lines.append('    c.execute(' + q34 + 'DELETE FROM alerts' + q34 + ')')
calc_lines.append('    today = datetime.now().date()')
calc_lines.append('    c.execute(' + q34 + 'SELECT sp.product_code, sp.quantity, sp.ship_date FROM shipping_plan sp' + q34 + ')')
calc_lines.append('    plans = c.fetchall()')
calc_lines.append('    for plan in plans:')
calc_lines.append('        product_code = plan[0]')
calc_lines.append('        quantity = plan[1]')
calc_lines.append('        ship_date = datetime.strptime(plan[2], ' + q39 + '%Y-%m-%d' + q39 + ').date() if plan[2] else today')
calc_lines.append('        days_remaining = (ship_date - today).days')
calc_lines.append('        c.execute(' + q34 + 'SELECT COALESCE(SUM(quantity), 0) FROM schedules WHERE work_order_no IN (SELECT order_no FROM work_orders WHERE product_code=?) AND task_status != ?' + q34 + ', (product_code, ' + q39 + 'cancelled' + q39 + '))')
calc_lines.append('        scheduled_qty = c.fetchone()[0] or 0')
calc_lines.append('        shortage = quantity - scheduled_qty')
calc_lines.append('        if days_remaining <= 3 and shortage > 0:')
calc_lines.append('            level = ' + q39 + 'red' + q39)
calc_lines.append('        elif days_remaining <= 7 and shortage > quantity * 0.5:')
calc_lines.append('            level = ' + q39 + 'yellow' + q39)
calc_lines.append('        else:')
calc_lines.append('            level = ' + q39 + 'green' + q39)
calc_lines.append('        message = product_code + ' + q39 + ' needs ' + q39 + ' + str(int(shortage)) + ' + q39 + ' more, ' + q39 + ' + str(days_remaining) + ' + q39 + ' days left' + q39)
calc_lines.append('        c.execute(' + q34 + 'INSERT INTO alerts (product_code, alert_level, due_date, quantity, scheduled_qty, shortage_qty, days_remaining, message, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' + q34 + ', (product_code, level, plan[2], quantity, scheduled_qty, shortage, days_remaining, message, ' + q39 + 'active' + q39 + '))')
calc_lines.append('    conn.commit()')
calc_lines.append('    count = len(plans)')
calc_lines.append('    conn.close()')
calc_lines.append('    return count')
calc_lines.append('')
calc_lines.append('def back_calculate_semi():')
calc_lines.append('    conn = get_connection()')
calc_lines.append('    c = conn.cursor()')
calc_lines.append('    c.execute(' + q34 + 'SELECT sp.product_code, sp.quantity, sp.ship_date FROM shipping_plan sp' + q34 + ')')
calc_lines.append('    plans = c.fetchall()')
calc_lines.append('    new_orders = 0')
calc_lines.append('    for plan in plans:')
calc_lines.append('        product_code = plan[0]')
calc_lines.append('        quantity = plan[1]')
calc_lines.append('        ship_date = plan[2]')
calc_lines.append('        c.execute(' + q34 + 'SELECT child_product_code, child_product_name, quantity, process_team FROM bom WHERE parent_product_code=?' + q34 + ', (product_code,))')
calc_lines.append('        children = c.fetchall()')
calc_lines.append('        for child in children:')
calc_lines.append('            child_code = child[0]')
calc_lines.append('            child_name = child[1]')
calc_lines.append('            bom_qty = child[2] if child[2] else 1')
calc_lines.append('            required_qty = quantity * bom_qty')
calc_lines.append('            c.execute(' + q34 + 'SELECT production_days, lead_days FROM production_cycles WHERE product_code=?' + q34 + ', (child_code,))')
calc_lines.append('            cycle = c.fetchone()')
calc_lines.append('            prod_days = cycle[0] if cycle else 1')
calc_lines.append('            lead_days = cycle[1] if cycle else 0')
calc_lines.append('            ship_dt = datetime.strptime(ship_date, ' + q39 + '%Y-%m-%d' + q39 + ') if ship_date else datetime.now()')
calc_lines.append('            due_dt = ship_dt - timedelta(days=lead_days)')
calc_lines.append('            due_str = due_dt.strftime(' + q39 + '%Y-%m-%d' + q39 + ')')
calc_lines.append('            order_no = ' + q39 + 'BC-' + q39 + ' + product_code + ' + q39 + '-' + q39 + ' + child_code')
calc_lines.append('            c.execute(' + q34 + 'SELECT id FROM work_orders WHERE order_no=?' + q34 + ', (order_no,))')
calc_lines.append('            if not c.fetchone():')
calc_lines.append('                c.execute(' + q34 + 'INSERT INTO work_orders (order_no, product_code, product_name, quantity, due_date, priority, status, source) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' + q34 + ', (order_no, child_code, child_name, required_qty, due_str, ' + q39 + 'P1' + q39 + ', ' + q39 + 'pending' + q39 + ', ' + q39 + '' + q39 + '))')
calc_lines.append('                new_orders += 1')
calc_lines.append('    conn.commit()')
calc_lines.append('    conn.close()')
calc_lines.append('    return new_orders')
calc_lines.append('')
calc_lines.append('def calculate_quantity(hours, capacity_per_hour):')
calc_lines.append('    if hours and capacity_per_hour:')
calc_lines.append('        return hours * capacity_per_hour')
calc_lines.append('    return 0')

w('utils/calc.py', chr(10).join(calc_lines))

# ===== 3. Initialize DB with default teams =====
from utils.db import get_connection
conn = get_connection()
c = conn.cursor()
teams = [
    ('前段', '班组长', '', '常白班', '08:00', '17:00'),
    ('焊接', '班组长', '', '常白班', '08:00', '17:00'),
    ('扣压', '班组长', '', '常白班', '08:00', '17:00'),
    ('装配包装', '班组长', '', '常白班', '08:00', '17:00'),
]
for t in teams:
    c.execute('INSERT OR IGNORE INTO teams (name, leader, members, shift_type, shift_start, shift_end) VALUES (?, ?, ?, ?, ?, ?)', t)
conn.commit()
conn.close()
print('Default teams created')

print('All builder2 files done!')